name: Run Azure Login with OIDC
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    AZURE_FUNCTIONAPP_NAME: "bff-competence-test" # set this to your function app name on Azure
    AZURE_FUNCTIONAPP_RESOURCE_GROUP: "rg-competence-test" # set this to your resource group name on Azure
    AZURE_FUNCTIONAPP_PACKAGE_PATH: "./api" # set this to the path to your function app project, defaults to the repository root
    DOTNET_VERSION: "6.0.x"

permissions:
    id-token: write
    contents: read
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Az CLI login"
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  enable-AzPSSession: true

            - name: Get publish Profile
              id: publishprofile
              uses: azure/powershell@v2
              with:
                  inlineScript: |
                      $profile = Get-AzWebAppPublishingProfile `
                        -ResourceGroupName ${{ env.AZURE_FUNCTIONAPP_RESOURCE_GROUP}} `
                        -Name ${{ env.AZURE_FUNCTIONAPP_NAME }}
                      $profile = $profile.Replace("`r", "").Replace("`n", "")
                      "profile=$profile" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                  azPSVersion: "latest"

            - name: "Checkout GitHub Action"
              uses: actions/checkout@v3

            - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: "Resolve Project Dependencies Using Dotnet"
              shell: bash
              run: |
                  pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
                  dotnet build --configuration Release --output ./output
                  popd

            - name: "Run Azure Functions Action"
              uses: Azure/functions-action@v1
              id: fa
              with:
                  app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
                  package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
                  publish-profile: ${{ steps.publishprofile.outputs.publishprofile }}

            - name: Reset publish Profile
              uses: azure/powershell@v1
              with:
                  inlineScript: |
                      $profile = Reset-AzWebAppPublishingProfile `
                        -ResourceGroupName ${{ env.AZURE_FUNCTIONAPP_RESOURCE_GROUP }} `
                        -Name ${{ env.AZURE_FUNCTIONAPP_NAME }}
                      $profile = ""
                  azPSVersion: "latest"